[package]
name = "mercado_csv"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.42"
csv = "1.2.1"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
rfd = "0.15.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
